server:
  port: 9002

#thymeleaf
spring:
  thymeleaf:
    cache: false  
    
#mysql setting
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/angel
    username: angel
    password: a1234
    
#jpa setting
  jpa:
    hibernate:
      ddl-auto: update
    generate-ddl: true
    show-sql: true
    database: mysql
    database-platform: org.hibernate.dialect.MySQLDialect